module.exports = [
  'Brazilian rice and beans',
  'Pasta Bolognese',
  'Pasta Pesto',
  'Pasta Alfredo',
  'Tortei',
  'Raviolli',
  'Leek risotto',
  'Aspargus risotto',
  'Portuguese pizza',
  'Brocoli pizza',
  'California pizza',
  'Canja',
  'Pumpkin soup',
  'Vegetables soup',
  'Minestrone soup',
  'Pea soup',
  'Lentils soup',
  'Beans soup',
  'Burrito in the oven',
  'Rice with lentils Bolognese salsa, cheese, and chips in the oven',
  'Ramen',
  'Yakisoba',
  'Hot Dog',
  'Stuffed potato',
  'Spanish tortilla',
  'Pancakes',
  'Lentils Bolognese',
  'Ala Minuta',
  'Sandwich',
  'Burrito bowl',
  'Polenta with sauce',
  'Falafel pita',
  'Falafel plate',
  'Stuffed belpepper',
  'Fondue',
  'Lasagna bolognese',
  'Stuffed pumpkin',
  'Zucchini pizza',
  'Ensopadinho de batata',
  'Mashed potato',
  'Escondidinho',
  'Carreteiro de linguiça',
  'Carreteiro de grão de bico',
  'Strogonoff',
  'Ervilha torta com ovo e molho vermelho',
  'Japo tofu vegetables',
  'Curry with tofu and vegetables, and rice',
  'Arepas with beans, avocado and banana'
];
